    CONSTANT wall=0x01
    CONSTANT goal=0x02
    CONSTANT item=0x04
    CONSTANT fire=0x05
    CONSTANT boundary = 0x0F
    CONSTANT onevolt_hex = 0x1b
    CONSTANT move_penalty = 0xFD
    CONSTANT item_reward = 0x0C
    CONSTANT goal_reward = 0x63
    CONSTANT fire_reward = 0xF9
    
    CONSTANT move_penalty_L = 0xFD 
    CONSTANT move_penalty_H = 0xFF
    CONSTANT fire_reward_L = 0xF9
    CONSTANT fire_reward_H = 0xFF
