movlw  0x57
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x58
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x59
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x5a
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x5b
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x5c
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x5d
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x5e
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x5f
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x60
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x61
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x62
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x63
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x64
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x57
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe5
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x58
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe5
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x59
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe5
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x5a
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe5
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x5b
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe5
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x5c
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe5
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x5d
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe5
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x5e
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe5
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x5f
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe5
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x60
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe5
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x61
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe5
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x62
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe5
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x63
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe5
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x64
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe5
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
