movlw  0x7
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xeb
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x8
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xeb
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x9
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xeb
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0xa
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xeb
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0xb
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xeb
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0xc
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xeb
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0xd
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xeb
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x7
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xea
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0xc
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xea
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0xd
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xea
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x6
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe9
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0xd
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe9
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x6
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x14
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x15
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x17
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x18
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x19
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x1f
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x20
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x21
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x22
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x23
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x24
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x2b
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x2c
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x2f
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x30
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x31
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x32
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x37
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x38
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x39
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x3a
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x3b
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x3c
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x45
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x46
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe8
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x7
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe7
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x13
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe7
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x19
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe7
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x1e
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe7
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x1f
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe7
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x25
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe7
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x2c
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe7
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x2d
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe7
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x2e
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe7
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x36
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe7
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x37
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe7
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x3d
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe7
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x45
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe7
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x46
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe7
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x47
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe7
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x8
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x9
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0xa
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0xb
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x12
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x1e
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x25
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x2c
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x2d
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x36
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x3d
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x46
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe6
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0xc
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe5
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0xd
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe5
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x12
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe5
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x1e
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe5
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x26
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe5
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x2c
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe5
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x36
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe5
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x38
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe5
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x3d
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe5
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x3e
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe5
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0xd
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe4
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x12
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe4
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x26
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe4
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x2c
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe4
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x36
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe4
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x38
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe4
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x39
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe4
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x3a
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe4
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x3b
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe4
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x3c
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe4
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x3d
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe4
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0xd
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe3
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x12
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe3
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x1e
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe3
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x26
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe3
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x2c
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe3
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x36
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe3
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x6
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe2
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0xd
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe2
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x12
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe2
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x1e
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe2
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x25
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe2
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x2c
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe2
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x36
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe2
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x45
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe2
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x46
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe2
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x6
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe1
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x7
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe1
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0xc
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe1
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x13
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe1
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x14
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe1
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x18
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe1
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x19
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe1
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x1f
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe1
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x24
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe1
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x2c
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe1
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x2d
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe1
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x37
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe1
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x38
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe1
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x3d
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe1
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x45
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe1
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x46
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe1
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x47
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe1
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x8
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe0
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x9
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe0
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0xa
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe0
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0xb
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe0
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x14
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe0
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x15
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe0
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x16
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe0
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x17
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe0
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x18
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe0
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x20
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe0
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x21
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe0
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x22
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe0
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x23
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe0
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x2b
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe0
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x2d
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe0
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x2e
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe0
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x2f
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe0
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x30
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe0
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x38
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe0
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x39
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe0
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x3a
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe0
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x3b
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe0
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x3c
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe0
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
movlw  0x46
movwf  LATE
movlw  0x0A 
call  add_tiny_delay 
movlw  0xe0
movwf  LATD
movlw  0x0A 
call  add_tiny_delay 
